name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: michaellikens
